memo_pj/memo/urls.py
from django.urls import path
from . import views

app_name = 'memo'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo'),
]

memo_pj/memo_pj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memo.urls')),
]

memo_pj/memo/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

memo_pj/memo/forms.py
from django.forms import ModelForm
from .models import Memo

class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

memo_pj/memo/views.py
from django.shortcuts import render, redirect
from .models import Memo
from django.shortcuts import get_object_or_404
from .forms import MemoForm
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    memos = Memo.objects.all().order_by('-updated_datetime')
    return render(request, 'memo/index.html', {'memos': memos})

def detail(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)    
    return render(request, 'memo/detail.html', {'memo': memo})

def new_memo(request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('memo:index')
    else:   
        form = MemoForm
    return render(request, 'memo/new_memo.html', {'form': form })

@require_POST #request.method=POSTの時のみ実行される
def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    memo.delete()
    return redirect('memo:index')    

def edit_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('memo:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'memo/edit_memo.html', {'form': form, 'memo':memo })

memo_pj/templates/memo/detail.html
<div>
    <a href="{% url 'memo:index' %}">ホームに戻る</a>
  </div>
  
<h2>{{ memo.title }}</h2>
<div>
  {{ memo.text | linebreaks | urlize }}
</div>

<button><a class="btn" href="{% url 'memo:edit_memo' memo_id=memo.pk %}">編集</a></button>

<form method="post" action="{% url 'memo:delete_memo' memo_id=memo.pk %}">{% csrf_token %}
  <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
</form>  

memo_pj/templates/memo/edit_memo.html
<div>
    <a href="{% url 'memo:detail' memo_id=memo.id %}">戻る</a>
  </div>
  
  <form action="{% url 'memo:edit_memo' memo_id=memo.id %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn" type="submit">保存</button>
  </form> 

memo_pj/templates/memo/index.html
<a class="btn" href="{% url 'memo:new_memo' %}">新規メモ作成</a>

{% for memo in memos %}
<a href="{% url 'memo:detail' memo_id=memo.id %}" class="memo-title">
  <div>
    {{ memo }}
    <span class="updated_datetime">{{ memo.updated_datetime }}</span>
  </div>
</a>
{% endfor %}

memo_pj/templates/memo/new_memo.html
<div>
  <a href="{% url 'memo:index' %}">ホームに戻る</a>
</div>

<form action="{% url 'memo:new_memo' %}" method="POST">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn">保存</button>
</form>